### PR TITLE
Travis CI builds

### PR DESCRIPTION
**Pull request by QuLogic**
As noted in issue #2, I started with @khaledhosny's work and had to make a few changes: a) patch `ZipPrivate` to work with older zlib (it's pretty simple); b) switch to a newer Qt PPA as it doesn't build with 5.0.z; c) switch to a newer compiler (because again issues compiling).

I enabled parallel building because serial builds takes almost 50 minutes (the limit on Travis). I tried several # of processors but since Travis has limited CPU and RAM, anything above 8 or so has a flaky speedup. However, I've found that clang has a tendency to OOM, so I reduced the number of processors when building with it.

I decided to just [patch OpenSceneGraph](https://github.com/QuLogic/ScribusCTL/commit/dbbed93e65753cec234de89a943313ca778893b3) so that it works with clang.

### CODE REVIEW

**Comment by QuLogic** [comment]
Note that clang has a tendency to get OOM-killed even with the reduced parallelism. It would be nice to switch to the container based infrastructure where limits are a little higher, but most Scribus dependencies are not whitelisted yet.

**Comment by QuLogic** [comment]
I changed the clang build to only use serial. It takes a while longer, but hopefully won't OOM.

**Comment by QuLogic** [comment]
Sorry for the extra builds, but I realized that the zlib patch didn't work quite right.

**Comment by QuLogic** [comment]
I squashed everything since a lot of it was reverted once using the Trusty servers. I also noticed that some import plugins were not building due to missing dependencies.

However, I tested it out locally, and it seems that the code is currently buggy when using those libraries and likely won't compile.

**Comment by QuLogic** [comment]
Can master be re-synced with svn? The build issue with the importers should be [fixed](http://scribus.net/websvn/revision.php?repname=Scribus&path=%2Ftrunk%2FScribus%2Fscribus%2Fplugins%2Fimport%2Fpub%2FCMakeLists.txt&rev=20245&peg=20245).

**Comment by luzpaz** [comment]
@QuLogic, I expect @andreas-vox to make that happen if/when he dedicates time to it this weekend.

**Comment by luzpaz** [comment]
@andreas-vox resynced. I was able to build scribusctl on osx no problem.

**Comment by luzpaz** [comment]
.travis.yml was added to master so @andreas-vox just needs to resync to merge this. Thanks for the PR

**Pull request closed without merging**
