### PR TITLE
Last Workable RTL patch (need little work)

### PR DESCRIPTION
**Pull request by moceap**

### CODE REVIEW

**Comment by luzpaz** [comment]
Thanks @moceap !  
When you say: "Last Workable RTL patch" can you explain what you mean exactly?

**Comment by moceap** [comment]
There is a many tries to support Arabic (and other RTLs) in Scribus, and this is the last (most developed) patch.

https://build.opensuse.org/package/show/home:moceap/Scribus

And I improve it to be included in trunk , and it need work to :
- Fix some building issues.
- Extract (fribidi - harfbuz) out of it.

@luzpaz @andreas-vox

**Comment by luzpaz** [comment]
@moceap looks like the patches have harfbuzz and fribidi in them. So perhaps I'm misinterpreting your words  
`And I improve it to be included in trunk , and it need work to : Extract (fribidi - harfbuz) out of it.`  
Are you planning on refining the patches ?

**Comment by moceap** [comment]
I mean the (fribidi , harfbuzz) included in the patch, the patch must improved to depend on external libs (fribidi ....) to keep them updated. :) just this..

Anyway I think we must fix building issues first ... Now I don't have enough time for that .. I hope if one of you doing that ..

@luzpaz @andreas-vox

**Comment by luzpaz** [comment]
CC @aoloe @FirasH @sarathms

**Comment by boardslayer** [comment]
I'd like to help with the hindi support if possible.

**Comment by luzpaz** [comment]
@nonson Hello! How would you like to contribute ?

**Comment by moceap** [comment]
First thing ... @andreas-vox accept the patch and sync to master ... then any changes from other contributors ..

**Comment by moceap** [comment]
@andreas-vox News?

**Comment by luzpaz** [comment]
@moceap he's been busy and has planned to make some time this weekend to work on CTL.

**Comment by luzpaz** [comment]
@moceap sorry I don't have the technical prowess to do this.

**Comment by andreas-vox** [comment]
I created a branch for your patch but it doesn't compile.
If you want I can commit the branch in this state, but as I see it, fixing it would go into the opposite direction to what I've planned for master.

**Comment by luzpaz** [comment]
@andreas-vox can you elaborate what your plans are for master. I [opened an issue](https://github.com/andreas-vox/ScribusCTL/issues/3) for you that could help others understand your agenda for this project. That way @moceap and others that have offered to help over the past month can see where they can contribute. What do you think?

**Comment by andreas-vox** [comment]
Hi, I committed this to branch "RTL". It compiles on OS/X Yosemite; if you face problems compiling, please report or send patch.

I haven't tested its functionality thoroughly, but it appears to display correct Arabic on canvas. Editing on canvas is not possible since the cursor position is off.

I plan to keep this branch as a reference but will not merge it back into master, since the chosen approach will make it difficult to realize the other goals of CTL. More details in issue #3.

**Pull request closed without merging**
